name: build-docker
on: [push]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Make the script executable
      - name: Make script executable
        run: chmod +x increment-version.sh

      # Increment version
      - name: Increment version
        run: ./increment-version.sh

      # Commit and push the new version
      - name: Commit and push the new version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add version.txt
          git commit -m "Increment version to $(cat version.txt)"
          git push

      # Create a tag
      - name: Create a tag
        run: |
          NEW_VERSION=$(cat version.txt)
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t julesdubayle/getting-started-app:${{ env.VERSION }} .

      # Push the Docker image
      - name: Push Docker image
        run: docker push julesdubayle/getting-started-app:${{ env.VERSION }}
